### ISSUE TITLE
Rethinking GDevelop versioning and release process

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#309] opened 2016-11-02 22:31 UTC
I think that the long delay between the stable updates of GDevelop is really long because of the way we manage them.

We should aim towards a more semantic versioning management: we used to increment the revision number for each version, the minor number for "almost big changes or not so big new features" and the major number for "big changes".

I suggest we change to this: for a given version X.Y.0
 - Fix bugs in versions X.Y.Z, Z > 0
 - Begin to work on and merge **new features** for the version X.(Y+1).0 (on a separate branch).

This way, we can release fixed version much quicker (not a lot of test required).

**Comment by 4ian** [comment] 2016-11-02 22:51
I think the root cause for the long time between each stable update is more related to the fact that releasing a new version is time consuming. Continuous integration servers always launch the tests which is nice, but the optimal situation would be to have continuous delivery, meaning that servers are building from scratch a Windows (at least) version of GDevelop each time we push something to master ("Nightly builds").
Nightly/automatic builds could be versioned with the latest number (X.Y.Z.aaaa, with aaaa being for example the git commit hash).

Right now, the process to deliver a new version on my side is to:
- `git pull` the latest master on OS X, build it (`make`), launch `./PackageForMacOS.sh` and upload the resulting `GDevelop.pkg` file. 
- Launch Windows on my bootcamp VM/dual boot, `git pull` the latest master, build it, launch `PackageForWindows.bat`.
- Launch the Ubuntu VM, launch the deployment script for each supported release of Ubuntu.

+ updated the Inno Setup installation file from time to time, fetch the latest translations.

So from the start to the end, it's taking at least 1h30/2h or more if something goes wrong or if a hotfix must be deployed just after the release ^^

So I'm quite interested in changing the versioning scheme to do more frequent release, and I'm also interested in automating more things or finding web services that could do builds. AppVeyor could be used to build the windows version, if it's quick enough.

**Comment by 4ian** [comment] 2016-11-02 22:55
And also announcing the version on the forum (english/french) + uploading the xml files (english/french) on the website for the automatic update checker. :) (~15/20minutes)

**Comment by victorlevasseur** [comment] 2016-11-02 23:13
I think we can take a look at what the SFML dev team uses for releasing SFML (and the unofficial nightlies).

**Comment by victorlevasseur** [comment] 2016-11-03 15:36
Currently investigating buildbot, the continuous integration and deployment system that the SFML dev team uses. Really easy and powerful (work with a master server and workers/slaves on normal computers). I managed to make a successful compilation of GDevelop with my Fedora as a slave and my VPS as a master. It also has a nice web UI. :)

**Comment by 4ian** [comment] 2016-11-03 21:51
Impressive! Is it easy to share a configuration for buildbot? Also maybe there are some companies offering "buildbot as a service" or something like this - I don't mind spending a few bucks on a service that would give us a slave windows machine to compile GDevelop on it.
Thinking about it, I could setup a windows machine on my Amazon or Azure account. 

It would be really awesome to have a nightly build made each time a change is pushed :) Releasing a new version would be easier and anyone interested could download the latest changes.

**Comment by victorlevasseur** [comment] 2016-11-03 21:57
Just need a repository to share the config (and hide the passwords for the slaves in a git-ignored python file).

**Comment by 4ian** [comment] 2016-11-03 22:18
What is the provisioning/setup needed to be done on a slave to make it buildbot ready? And what details should I share with you so that your master is able to use the slave?

A t2.micro instance (1 vCPUs, 2.5 GHz, Intel Xeon Family, 1 GiB memory) on Amazon with Windows Server 2016 is $13.18 (Storage is paid separately, it's quite cheap). Less than 1GiB of memory sounds low for compiling, but if it works that's ok! :) 

EDIT : I'm launching one now, will share with you the access if you want to make some tests.

**Comment by 4ian** [comment] 2016-11-03 22:28
I have a Windows server launched on Amazon, I'll send you the credentials to connect to it. :)
You can play a bit with it and see if you manage to have it to be a buildbot slave that compiles GD!
(I'm even wondering if I should stop using my Windows installation and just have an instance like this).

**Comment by victorlevasseur** [comment] 2016-11-03 22:49
I already successfully built GD on a Raspberry Pi, so I think 1 GiB is enough.

**Comment by 4ian** [comment] 2016-11-03 22:50
Sounds good then!

**Comment by victorlevasseur** [comment] 2016-11-03 23:51
Currently compiling GDevelop with a worker on your instance. Seems that the compiler uses a lot pagefile.sys (not enough RAM) but doesn't seem to have a big impact on the building performances (still better than on my Windows computer if I use 1 core).

**Comment by 4ian** [comment] 2016-11-04 00:00
Yay! I would be interested in any good documentation/tutorial you've found about setting up Buildbot, I'd like to see how it works :)

**Comment by victorlevasseur** [comment] 2016-11-04 00:01
The tutorial on the main website is really good: I mean, I started yesterday and I'm already able to get something working (GDevelop builds successfully, the deployment part remains though).

**Comment by victorlevasseur** [comment] 2016-11-04 00:40
The Windows instance seems to slow down after a long time (~20 minute) of heavy use. Is it because of this: http://stackoverflow.com/questions/28984106/whats-is-cpu-credit-balance-in-ec2 ?

**Comment by 4ian** [comment] 2016-11-04 09:43
3h looks a bit long for a build indeed! Maybe an instance with a fixed performance would be more adapted. The thing is that most of the time the instance will be idle so maybe just get an instance that is allowed to burst more CPU credit.

**Comment by victorlevasseur** [comment] 2016-11-04 11:08
A fixed performance instance is useless. By the way, the build mode is
currently incremental, so buildbot doesn't need to rebuild GDevelop
entirely. I can Also schedule 1 build per day. Also, I probably burst a lot
of CPU credits when configuring the instance. I'll launch a full rebuild
tonight to test again.

Le ven. 4 nov. 2016 10:43, Florian Rival <notifications@github.com> a
écrit :

**Comment by MickaelH974** [comment] 2016-11-04 16:58
I have recently build GD on Raspberry Pi 2 and I confirm it's working with 1GB (with swap to 512mb but I don't know if it was really necessarily). It takes about 5 hours ;-)

**Comment by 4ian** [comment] 2016-11-05 22:14
@victorlevasseur I see your buildbot master is down, is there something wrong going on?
For deployment, I guess we could have a rather simple script that launch `PackageForWindows.bat` and once it's done, upload the resulting installer and zip file to an online storage. For example an Amazon S3 bucket (https://aws.amazon.com/getting-started/tutorials/backup-to-s3-cli/)

I guess it would be good enough as a starting point, we would have daily GDevelop builds! Once a version is good enough, we can bump the version and wait for the next build to be done to release it for Windows.

**Comment by victorlevasseur** [comment] 2016-11-06 18:54
Had some trouble to update the config. It's done now. :) I'll soon upload the config on github. By the way, there's no need for a big bat script

**Comment by victorlevasseur** [comment] 2016-11-07 18:36
The easiest would be to keep the nightlies on the same server as the master buildbot as buildbot provides a simple script to upload a file from a worker to the master. You can then redirect a subdomain of compilgames.net (nightlies / nightly ?) to my VPS (and another one to the buildbot).

**Comment by victorlevasseur** [comment] 2016-11-08 10:28
See nightlies.gd.victorlevasseur.com

**Comment by 4ian** [comment] 2016-11-15 22:00
@victorlevasseur I've realized that updating the version is triggering the recompilation of quite a lot of files. That's a bit unfortunate as it's making development time longer when you switch between Git branches or pulling new commits. The real solution would be to have fewer dependencies on this file but maybe we should have an option to deactivate the branch inserted in the version string? Or on the contrary, deactivate it by default and have a CMake option activated on the continuous integration workers to enable this for the nightlies?

What do you think?

**Comment by victorlevasseur** [comment] 2016-11-15 22:02
Good idea, will update this

Le mar. 15 nov. 2016 23:00, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment] 2016-11-15 22:04
👍 Awesome

**Comment by victorlevasseur** [comment] 2016-11-15 22:08
But I think an option to disable the auto versioning is more appropriate
than an option to enable it.

Le mar. 15 nov. 2016 23:04, Florian Rival <notifications@github.com> a
écrit :

**Comment by victorlevasseur** [comment] 2016-11-20 00:28
Done in 7e23652.

**Comment by 4ian** [comment] 2016-11-23 08:24
Thanks! 👍

**Comment by victorlevasseur** [comment] 2016-12-30 11:15
Can you restart the server again? There's definitely a problem with it... :(

**Comment by 4ian** [comment] 2016-12-30 13:52
Done. CPU Credit Balance is 0 again since 2 days.

**Comment by 4ian** [comment] 2018-05-26 00:16
Closing this as it's not relevant anymore :) GDevelop 5 takes 5 minutes to be deployed with auto update to anyone.
Any work to improve GDevelop 4 releases is still welcome!

**Closed by 4ian** 2018-05-26 00:16 UTC
Labels: question
