### ISSUE TITLE
Browser cache preventing scripts from updating in scene preview mode

### ISSUE THREAD

**Issue by brylie** [4ian/GD#253] opened 2016-02-26 17:50 UTC
I have a scene with a simple script, seen in the following screenshot:
![gdevelop-eventfail](https://cloud.githubusercontent.com/assets/17307/13360420/e1ca08de-dcc1-11e5-9c2d-d2d7008201d3.png)

```
// Condition
Circle is being dragged
  Circle distance to circleTarget is below 50 pixels
```

```
// Actions
do =CircleTarget.X(); =CircleTarget.Y() to the position of Circle
do =50 to the opacity of Circle
```

When viewing the scene preview, neither of the actions are triggered. However, everything works as expected when I export the game as HTML.
# Environment
- OS: Ubuntu 15.10
- GD: 4.0.89.0
- Browser: FF 44.0.2

**Comment by victorlevasseur** [comment] 2016-02-26 17:51
Refresh your webbrowser cache while previewing (Ctrl+F5 or Shift+F5 or
Alt+F5 depending of the webbrowser).

**Comment by brylie** [comment] 2016-02-26 17:55
OK, that worked. I used `Ctrl + Shift + R`. Is this a known bug?

**Comment by victorlevasseur** [comment] 2016-02-26 18:34
That's not a bug, it's just the webbrowser that uses a cached version of
some scripts instead of reloading them from the GDevelop files.

**Comment by brylie** [comment] 2016-02-27 00:51
Well, it may be a *usability bug*. In effect, an end user, including myself, is expecting their script to work without having to resort to cache clearing. 

Is there a possible work-around, so that the browser does not cache the project (e.g. using dynamic file names)?

**Comment by 4ian** [comment] 2016-02-27 12:29
Dynamic filenames (adding a random string basically in the GET request) would solve this indeed. This should be implemented in the HTML5 game exporter/previewer.

**Comment by 4ian** [comment] 2018-05-26 00:17
Closing as duplicate and should not happen in GDevelop 5 now :)

**Closed by 4ian** 2018-05-26 00:17 UTC
