### ISSUE TITLE
Light Extension : crash when previewed

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#127] opened 2015-05-13 22:31 UTC
Here is the gdb output : 
```
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x6bdc2635 in Light::AddTriangle(sf::Vector2<float>, sf::Vector2<float>, int
, std::vector<Wall*, std::allocator<Wall*> >&) ()
   from C:\Program Files (x86)\GDevelop\CppPlatform\Extensions\Light.xgdwe
#1  0x00000000 in ?? ()
```

**Comment by 4ian** [comment] 2015-05-13 22:31
Is this happening with any example?

**Comment by victorlevasseur** [comment] 2015-05-13 22:34
Yes, Dynamic Lights and Laser & Zombies
It seems that the crash occurs **when a light is inside a light obstacle**.

**Comment by 4ian** [comment] 2015-05-13 23:21
Ok, surely an edge case causing the crash :/ I guess a debug build would be useful to see precisely what's going on.

**Comment by 4ian** [comment] 2015-06-15 20:32
Do you know how to reproduce the bug? I wasn't able to make the lights crash when previewing the Physics with lights example nor the dynamic lights. (Not tried yet with Laser & Zombies).

**Comment by victorlevasseur** [comment] 2015-06-15 20:43
You can reproduce it by putting a light inside a light obstacle.

**Comment by victorlevasseur** [comment] 2015-07-11 12:26
I think this game suffers the same bug : http://forum.compilgames.net/viewtopic.php?f=4&t=6761&p=51764#p51753

**Comment by 4ian** [comment] 2015-07-14 03:25
Looks like a heisenbug, when I try with a Debug build, or even a RelWithDebInfo build, no crash on Windows. :( (Not sure the game is working properly though because using my virtual machine I have not proper rendering of the scene).

**Comment by 4ian** [comment] 2015-07-14 11:38
Fixed in https://github.com/4ian/GD/commit/a4de75d2516f8d46afa3e77687f91388606a6741 :smile: 
It was due to comparison between sf::Vector2f returning null even if the vectors were equal, surely a rounding error or something related to floating number precision.

**Closed by 4ian** 2015-07-14 11:38 UTC
