### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by abelnicolas1976** [4ian/GD#282] opened 2016-08-01 20:25 UTC
it closes when you open a scene (in earlier versions of Linux did not pass)

[gide.txt](https://github.com/4ian/GD/files/394709/gide.txt)

System:
Linux alpha 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
CPU: fx-8120
RAM: 16Gb
VGA: GT 430 (driver nvidia 361.42)

Gdevelop 4.0.92.0

**Comment by victorlevasseur** [comment] 2016-08-01 20:59
Does the bug happen with a project with events containing **no** conditions ? (just create an empty project, add an event with some actions in it and try to preview it).

**Comment by abelnicolas1976** [comment] 2016-08-02 13:11
there were no problems 

![cap1](https://cloud.githubusercontent.com/assets/20780609/17329521/60977db0-5899-11e6-9658-27dffc55ee88.png)

![cap2](https://cloud.githubusercontent.com/assets/20780609/17329540/6b773702-5899-11e6-98ef-31a66fdc6a2f.png)

**Comment by victorlevasseur** [comment] 2016-08-02 13:13
Interesting...

**Comment by victorlevasseur** [comment] 2016-08-16 10:48
Duplicate of #279. So I close this one. Go on #279 to follow the discussion.

**Closed by victorlevasseur** 2016-08-16 10:48 UTC
