### ISSUE TITLE
Player stuck when removing the platform he is on

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#79] opened 2015-01-30 12:44 UTC
The player is not totally stuck but fall very slowly and can jump at any moment).
Happens only in HTML5 games.

**Comment by 4ian** [comment] 2015-01-30 21:09
Strange that the behavior varies in native and HTML5 games as the code should be the same. I'll take a look!

**Comment by victorlevasseur** [comment] 2015-04-30 16:10
Should be tested again as you optimized the platformer automatism.

**Comment by 4ian** [comment] 2015-04-30 21:45
Mmm, optimisations were made mainly on the implementation to avoid using `for in` loops that JS engines can't JIT compile and optimize. So normally the behaviors of objects didn't change and the issue is still here!

**Comment by 4ian** [comment] 2018-05-26 00:04
Closing as this should not be happening now. Feel free to open a new issue if there is still a reproducible issue :)

**Closed by 4ian** 2018-05-26 00:04 UTC
