### ISSUE TITLE
Scrolling does not work properly on Windows

### ISSUE THREAD

**Issue by Nnarol** [4ian/GD#497] opened 2018-05-20 23:00 UTC
## When using GDevelop 5 (Beta 29) on Windows, scrolling with the mouse wheel also activates zooming, even if Ctrl is not pressed.

The attached images show that the scrollbars are moving.

Simply using the mouse wheel, **zooming activates** parallelly to vertical scrolling:

![scrolling_normal](https://user-images.githubusercontent.com/24636189/40284497-4b53088c-5c90-11e8-8050-4020f53013a3.gif)
<br />
When holding the Alt key down whilst scrolling with the mouse wheel, **zooming** happens again, and curiously, although **horizontal scrolling is active as well, it is very slow**.
It looks as if actually only zooming happens, but with a constant focus point, since the direction is the same regardless of the mouse pointer position:

![scrolling_alt_pressed](https://user-images.githubusercontent.com/24636189/40284519-a369053a-5c90-11e8-91e2-386ec1d69807.gif)
<br />
Zooming via the Ctrl key and the mouse wheel seems to work just as expected, with neither of the scroll bars moving:

![scrolling_ctrl_pressed](https://user-images.githubusercontent.com/24636189/40284557-34c79e88-5c91-11e8-9851-ebfdaef608c4.gif)

This did not happen to me on Linux.
I can not try it on a Mac, since I don't have one.

**Comment by 4ian** [comment] 2018-05-21 02:45
Can you try with the latest version beta34? @blurymind have remodeled the way the scrolling work in the latest beta version so it might be better?

**Comment by blurymind** [comment] 2018-05-21 08:32
Ah that is strange - I remember fixing this. Does it also happen on the latest beta version?

**Comment by Nnarol** [comment] 2018-05-21 09:11
I have to check, thanks for the tip! Actually, before filing the issue, I checked if I had the same version that the website offers for download, and it was beta 29.
Is beta 34 the latest master, but 29 the one on the website?

**Comment by Nnarol** [comment] 2018-05-21 12:17
It will take some time before I can test it, since my dev toolchain is not set up on Windows yet.

**Comment by 4ian** [comment] 2018-05-21 19:17
Oops I forgot to update the links on the website. Should be good now :) 
You can always download the latest version from GitHub in case you have a doubt from this page: https://github.com/4ian/GD/releases

**Comment by Nnarol** [comment] 2018-05-21 20:29
Thanks a lot! I'll try the downloaded version then!

**Comment by Nnarol** [comment] 2018-05-21 20:52
Nope, it still behaves the same, unfortunately.

I also tried it this time with the touchpad. It is buggy, but somehow differently: 

- When trying to scroll (up and down), it scrolls much slower than with the mosue wheel, but zooms really fast.

- Wiping left and right causes smooth, but fast zooming, also sideways scrolling at a normal speed.

- Scrolling with the Alt button pressed just blocks both scrolling and zooming.

- Scrolling with Ctrl pressed results in a really slow, jerky zooming. I suspect that the program tries to carry out several actions simultaneously, because the driver signals a movement in more than one direction during the wipe gesture .

Touchpads are tricky sometimes, no matter what the use case. Different drivers cause them to behave vastly differently.

**Comment by blurymind** [comment] 2018-05-22 09:12
I can look into this in the weekend. Are there any steps that could help reproduce the problem?
It doesn't behave that way on my computer with windows 10 - in terms of scrolling. I havent yet added alt modifier to pan when scrolling or properly tested with touchpad. This is something that could be improved - but I need to be able to reproduce the bad behavior in order to fix it.

I hope this is not a computer specific issue

**Comment by Nnarol** [comment] 2018-05-22 17:51
@blurymind I tried it on Windows 8.1 . My mouse is a Bloody V4M, with no special drivers installed on the PC, although the mouse's memory does contain flashed settings from configuration software.
I think I have a really cheap mouse lying around, although if I remember correctly, its wheel is long dead, so I may or may not be able to try that one out.
Is there any log that GDevelop provides that I can include to help you?
I would also gladly try to help debugging this, but I've never programmed in JavaScript before and I just installed VS Code, it still needs more configuration until I can properly use it for debugging.

**Comment by blurymind** [comment] 2018-05-23 08:28
Will have a crack at this in the weekend. I need you to help me with testing

**Comment by Nnarol** [comment] 2018-05-23 08:51
I already built newIDE and tried it from the browser. Not that there were no roadblocks, but I managed to resolve most of them.
Playing with the code is one thing, but I would rather not implement fixes using a technology I am not familiar with. What I meant was discovering the error and communicating it with you or others. However, for doing that efficiently, I would need a debugger, which is what I'm working on.
Unfortunately, I have quite some work to do during the week, and on saturday, I'll be doing a workshop (using GDevelop :D), so my time will be limited.
BTW where can we communicate so that we don't pollute the Github issue with irrelevant details?

**Comment by blurymind** [comment] 2018-05-24 09:53
@Jeje2201 do you also get this issue? Also what version of windows were you on?

**Comment by Jeje2201** [comment] 2018-05-24 11:40
Am I a beta tester now ? haha jk
What do you want me to try ? Zooming with the mouse weel, and same with alt press and same with ctrl press, using recent release beta 36 on my computer ?

**Comment by Jeje2201** [comment] 2018-05-24 14:55
I don't know if this is the test you asked for ._.
I tried the different zoom you recaped.
Im using Windows 10, Gd5 Beta 34, on a laptop, and I use a normal mouse, just to make sure im not an alien.
You can see what I pressed but to be sure:
- I zoomed without pressing anything, it zoomed while moving vertically
- I zoomed while pressing alt, it zoomed while moving horizontaly
- I zoomed while pressing ctrl, it zoomed as a normal zoom without moving anything

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19387127/40493016-1afd3998-5f72-11e8-8062-bb930f11be4b.gif)

So it look like it's same as what @Nnarol showed on his first post ?

**Comment by blurymind** [comment] 2018-05-24 16:26
Ah I see. There must have been a regression somewhere along the way. I am now looking into this and will try to fix it

**Comment by blurymind** [comment] 2018-05-24 18:22
I made a pull request that fixes the problems.
Please let me know if it works for you:
https://github.com/4ian/GD/pull/500

:)

**Comment by 4ian** [comment] 2018-05-25 05:51
Can you check with beta 37 and let me know if it's better?

**Comment by Nnarol** [comment] 2018-05-25 06:02
Thanks for the work!

I checked it, and now it does behave consistently, albeit invertedly, if I'm not mistaken: now simply turning the mouse wheel zooms, and doing it while pressing Ctrl scrolls. Alt scrolling works as expected.

I think this is "inverted" based on what I got used to using other applications, for example browsers, where Ctrl + mouse wheel zooms, simply mouse wheel scrolls.

BTW, the new Piskel feature looks awesome :)

**Comment by blurymind** [comment] 2018-05-25 07:56
@Nnarol Ah glad it works now 👍 

When I was working on the scrolling logic, I was already thinking about integrating Piskel in Gdevelop. 

So the reason scrolling to zoom works without the need of modifier keys is:
- To be consistent with Piskel and all the other open source graphics software (Krita, Gimp, Blender etc)
- It's a design that enables complete navigation with only one hand and button - the middle mouse button can both scroll and pan. In some proprietary software that is not the case of course 

In the future it should ideally be configurable of course :) 

Btw you can change it by editing 
newIDE/app/src/UI/KeyboardShortcuts/index.js

With this last commit it is now more straightforward to change

Anyways we can close this issue now

**Comment by Nnarol** [comment] 2018-05-25 08:57
@blurymind I can see your reasoning, and am glad that this works now. Thank you again.

Indeed, I think this issue can be closed as well.

**Closed** 2018-05-25 12:51 UTC

**Comment by 4ian** [comment] 2018-05-25 16:19
Great explanation, thanks to both of you :)
@blurymind I guess your explanation could even be part of a wiki page about "Mouse usage in scene editor" :)

**Comment by blurymind** [comment] 2018-05-25 17:56
@4ian we can use it if you want to :)

**Comment by 4ian** [comment] 2018-05-25 18:33
Yes feel free to go and add it somewhere if you have time :)
