### ISSUE TITLE
G5 : Copy/paste or duplicate object, click on another objet in the list instead of validate the name make whole IDE to freeze

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#599] opened 2018-08-27 21:02 UTC
beta 48.

I tried to reproduce it in a basic example, but it doesn't happen anytime.

Often, when i duplicate an object, or copy/paste it in the object list, i trigger a freeze of the whole IDE (only way to exit is killing the window) :
After duplicating an object (or copy/past it on the same scene), the newly created object have the focus (to allow to change the its name). At this moment, if you don't validate the name (enter), then click on another object in the object list => (often)freeze. 
If you click on scene while the newly duplicated object has it name in edition (not validated) => freeze also (half of the time).

I also encounterred this bug by copying/pasting an object to another scene.

**Comment by 4ian** [comment] 2018-08-27 21:16
I tried to reproduce this now but I got the message telling that this object name is already taken (which is not a proper behavior btw 🤔)

**Comment by 4ian** [comment] 2018-08-27 21:45
Identified what can create this problem, fixing now

**Comment by 4ian** [comment] 2018-08-27 22:08
Fixed by 3be23212a6949069908b05708fe2301aa656470d 😊

A change to allow object renaming from objects editor added a while ago created an improper use of objects, leading to potentially an infinite loop due to a bad memory usage!
Should be all good in next version.. until I can release it **I recommend saving** before doing any renaming. Once rename is done, check that everything is ok and save again.
As usual, always do regular backups/copies of the game in separate files to be extra sure.

**Closed by 4ian** 2018-08-27 22:08 UTC

**Comment by 4ian** [comment] 2018-08-27 22:56
The fix is in beta49. Let me know if you still have an issue, but I'm confident there won't be any problem now :)

**Comment by KinkGD** [comment] 2018-08-27 22:58
i'll let you know as soon as possible.

**Comment by zatsme** [comment] 2018-08-28 08:51
Losing your work is the worst that can happen!  Maybe we can have automatic backups of our projects to allow for potential bugs and corrupt saves.  Project. 1, 2, 3, 4, 5 for example automatically saved every timescale/amount of changes configurable by user of course. Zat.
