### ISSUE TITLE
GD can not new project in ubuntu 17.10

### ISSUE THREAD

**Issue by timloo0710** [4ian/GD#392] opened 2017-09-30 16:18 UTC
My desktop is Ubuntu 17.10, 
----------------------
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful
--------------------
I was following the guide to complie source with CMake . 
 I run GD as following: 
 /GD/Binaries/Output/Release_Linux$ ./StartGDevelop.sh

When I new a project, 
It shows:
--------------------------
ERROR - ContextualIdentityService - Unknown version found in /home/timloo/.mozilla/firefox/wa7fp0qh.default/containers.json
Bool attribute "folderProject" not found, returning 0Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Child effects not found in SerializerElement::GetChild
The program 'GDIDE' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 45 error_code 10 request_code 2 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
-----------------------------------
Any Help?

Best Regards,Tim

**Comment by Lizard-13** [comment] 2017-09-30 16:25
I'm getting the same problem after compiling GD in Ubuntu 16.04 (officially supported version), I was thinking about deleting the entire directory and clone again, but it seems is not my fault :/

**Comment by dos1** [comment] 2017-12-22 01:47
Check out #340

**Comment by Nnarol** [comment] 2018-05-20 17:02
Hello!
I had the same problem (on Ubuntu 18.04), but I might have found a solution, that probably does not fit everyone though. Basically, I made sure that I'm using the GTK 3 GUI toolkit package and the GTK 3 development libraries for wxWidgets only, and threw out the GTK 2 ones:

sudo apt-get remove libwxgtk3.0-dev
sudo apt-get remove libgtk2.0-dev

sudo apt-get install libwxgtk3.0-gtk3-dev
sudo apt-get install libgtk-3-dev

If I am correct, the problem is with the newer versions of the wxWidgets library, nothing GDevelop creators can really change:

https://en.sfml-dev.org/forums/index.php?topic=21025.0

Hopefully this also solves the problem for you and others.
Cheers.

**Comment by 4ian** [comment] 2018-07-17 21:30
Closing this as it's getting old and it seems that there is a way to fix the issue!  Feel free to re-open if you have more details

**Closed by 4ian** 2018-07-17 21:30 UTC
Labels: GDevelop 4
